### ISSUE TITLE
++ add is wrong

### ISSUE THREAD

**Issue by johncburnham** [urbit/archaeology#11]
++ add :: add
  ~/ %add
  |= [a=@ b=@]
  ^- @
  ?: =(0 a)
    b
  $(a (dec a), b +(b))

should be

++ add :: add
  ~/ %add
|=  [a=@ b=@]
=+  c=0
|-  ^-  @
  ?: =(c a)
    b
  $(c +(c), b +(b))

and then change the doc here http://urbit.github.io/2013/08/22/Chapter-0-intro.html.

Add should be O(n) not O(n^2).

**Comment by twopir** [comment]
I'm willing to make this change, but I don't know how this makes add O(n) instead of n^2.

**Comment by twopir** [comment]
Oh, wait, I think I see it now. Introduce an accumulator "c" and don't go into dec?

**Comment by philipcmonk** [comment]
Exactly.

Philip Monk

**Comment by johncburnham** [comment]
we're holding off on doing this for now because:
a. it literally makes no difference (because it gets jet-propelled anyway)
b. we still have to test the change, and there are higher-priority things for us to be doing.

One of these days our intrepid band of nascent hoon programmers will go through and optimize all this stuff. Not because it makes any practical difference, but because it's just aesthetically nice to have functions be as clean and simple as possible.

**Comment by twopir** [comment]
That and some of us are sticklers for "correctness". I'll come back to this unless someone else knocks it out first.

**Comment by ikbrunel** [comment]
I just got an image of a Hoon dojo with a cohort of initiates writing test
suites for each others' Nock interpreters.

Katas on the mind...

On Oct 6, 2013, at 8:02 PM, johncburnham notifications@github.com wrote:

we're holding off on doing this for now because:
a. it literally makes no difference (because it gets jet-propelled anyway)
b. we still have to test the change, and there are higher-priority things
for us to be doing.

One of these days our intrepid band of nascent hoon programmers will go
through and optimize all this stuff. Not because it makes any practical
difference, but because it's just aesthetically nice to have functions be
as clean and simple as possible.

—
Reply to this email directly or view it on
GitHubhttps://github.com/urbit/urbit/issues/11#issuecomment-25783045
.
