### ISSUE TITLE
Cloning takes a long time

### ISSUE THREAD

**Issue by mrdomino** [urbit/archaeology#116]
The Urbit repo is pretty hefty. Perhaps we should pare it down somehow.

**Comment by yebyen** [comment]
Is there some way to identify the biggest git commits?

When I am dealing with flat files inside of directories, I just do:

`du -sch *|sort -h`

I don't get that kind of tree sense of things out of git objects.

```
yebyen@bono:/home/john/urbit/.git$ ls -A|xargs du -sch|sort -h
4.0K    branches
4.0K    config
4.0K    description
4.0K    HEAD
4.0K    packed-refs
8.0K    info
28K refs
32K logs
44K hooks
44K index
99M objects
99M total
yebyen@bono:/home/john/urbit/.git$ cd objects/
yebyen@bono:/home/john/urbit/.git/objects$ ls -A|xargs du -sch|sort -h
4.0K    info
99M pack
99M total
yebyen@bono:/home/john/urbit/.git/objects$ cd pack/
yebyen@bono:/home/john/urbit/.git/objects/pack$ ls -A|xargs du -sch|sort -h
208K    pack-6748bcae51dc5382b70a1b811e48dd9760e8eaee.idx
98M pack-6748bcae51dc5382b70a1b811e48dd9760e8eaee.pack
99M total
```

Since the majority of the commit is in a pack file, I don't see any way to pare it down in that sense.

Or did someone repack the github.com repo in some way, to fix your issue in the last 13 days?  I don't know if that is actually a thing.  Does your `.git/` directory look the same as mine above?

**Comment by yebyen** [comment]
You could always fork and squash all of the commits in your local branch

Staying in sync after that will require some git-fu
